server {
  listen 80;
  listen [::]:80;
  server_name jurcrawler.com.br www.jurcrawler.com.br;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
  }

  location / {
    return 503;
  }
}
